# .circleci/config.yml
version: 2.1
jobs:
  build:
    machine:
      image: android:202102-01
    # To optimize build times, we recommend "large" and above for Android-related jobs
    resource_class: large
    steps:
      - checkout
      - run:
          name: List Images
          command: |
            sdkmanager --list --verbose | grep system-images
      - run:
          name: Create avd
          command: |
            echo $ANDROID_HOME
            echo $JAVA_HOME
            pwd
            ls
            gradle -v
            gradle wrapper
            SYSTEM_IMAGE1="system-images;android-28;google_apis;x86"
            SYSTEM_IMAGE2="system-images;android-29;google_apis;x86"
            SYSTEM_IMAGE3="system-images;android-30;google_apis;x86"
            
            
            sdkmanager "$SYSTEM_IMAGE1"
            sdkmanager "$SYSTEM_IMAGE2"
            sdkmanager "$SYSTEM_IMAGE3"
            echo "no" | avdmanager --verbose create avd -n Device1 -k "$SYSTEM_IMAGE1"
            echo "no" | avdmanager --verbose create avd -n Device2 -k "$SYSTEM_IMAGE2"
            echo "no" | avdmanager --verbose create avd -n Device3 -k "$SYSTEM_IMAGE3"
      - run:
          name: Launch emulators
          command: |
            emulator -avd Device1 -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
            emulator -avd Device2 -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
            emulator -avd Device3 -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          background: true
      
      - run:
          name: Generate cache key
          command: |
            find . -name 'build.gradle' | sort | xargs cat |
            shasum | awk '{print $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          key: gradle-v1-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
      
      - run:
          name: Wait for emulator to start
          command: |
            circle-android wait-for-boot
      - run:
          name: Disable emulator animations
          command: |
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
      - run:
          name: Run UI tests (with retry)
          command: |
            MAX_TRIES=2
            run_with_retry() {
               n=1
               until [ $n -gt $MAX_TRIES ]
               do
                  echo "Starting test attempt $n"
                  sudo ./gradlew connectedDebugAndroidTest && break
                  n=$[$n+1]
                  sleep 5
               done
               if [ $n -gt $MAX_TRIES ]; then
                 echo "Max tries reached ($MAX_TRIES)"
                 exit 1
               fi
            }
            run_with_retry
      - run:
          name: Save test Reports
          command: |
            pwd
            ls -ltr
          when: always
      - store_artifacts:
          path: ~/project/app/build/reports
               
      - save_cache:
          key: gradle-v1-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
workflows:
  build:
    jobs:
      - build
